//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Housekeeper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersMaster
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public bool isAdmin { get; set; }
        public string Email { get; set; }
        public Nullable<bool> isEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
    }
}
